### ISSUE TITLE
Federation metrics are not pushed to Stackdriver

### ISSUE THREAD

**Issue by sesto** [Stackdriver/stackdriver-prometheus-sidecar#98]
I scrape with Prometheus several exporters (for example node-exporter) as well as `/federate` endpoint of another Prometheus instance. I can see all metrics being scraped and collected. When I try to push the metrics  to Stackdriver, I can see the metrics originated from the exporters being pushed. However,  the metrics from the`/federate` endpoint are never pushed to Stackdriver. No errors in the side car logs

**Comment by jkohen** [comment]
Thanks for the report, Sergei. Federated metrics aren't supported because we can't look up the metadata and monitored resource. This can't be solved within the sidecar. The recommended solution is to run the sidecar with each individual instance of Prometheus if possible.

We plan to make these things easier to diagnose in the future. Sorry for the confusion. /cc @davidbtucker
